# Project Objective

This project aims to analyze the patterns and disparities of HIV infections in New York City, focusing on how race/ethnicity, age group, gender and neighborhood influence the rate of contamination. The primary goal is to identify which groups are most affected as they will serve as good indication of where public health interventions could have a huge impact.

Importing all required libraries

In [ ]:
#importing packages needed

import requests
import pandas as pd
import json
from pathlib import Path

Reading the dataset of HIV AIDS Diagnosis by Gender, Neighborhood and Race Ethnicity. And creating a dataframe called df_Gender

In [8]:

df_Gender = pd.read_csv('Dataset/HIV_AIDS_by_Gender_by_Neighborhood_and_Race_Ethnicity.csv')
df_Gender

,YEAR,Borough,Neighborhood (U.H.F),SEX,RACE/ETHNICITY,TOTAL NUMBER OF HIV DIAGNOSES,"HIV DIAGNOSES PER 100,000 POPULATION",TOTAL NUMBER OF CONCURRENT HIV/AIDS DIAGNOSES,PROPORTION OF CONCURRENT HIV/AIDS DIAGNOSES AMONG ALL HIV DIAGNOSES,TOTAL NUMBER OF AIDS DIAGNOSES,"AIDS DIAGNOSES PER 100,000 POPULATION"
0,2010,NaN,Greenpoint,Male,Black,6,330.4,0,0,5,275.3
1,2011,NaN,Stapleton - St. George,Female,Native American,0,0,0,0,0,0
2,2010,NaN,Southeast Queens,Male,All,23,25.4,5,21.7,14,15.4
3,2012,NaN,Upper Westside,Female,Unknown,0,0,0,0,0,0
4,2013,NaN,Willowbrook,Male,Unknown,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
8971,2021,Staten\nIsland,Willowbrook,Male,Asian/Pacific\nIslander,2,24.2,0,0,0,0
8972,2021,Staten\nIsland,Willowbrook,Male,Black,0,0,0,NaN,0,0
8973,2021,Staten\nIsland,Willowbrook,Male,Latino/Hispanic,1,18.2,0,0,0,0
8974,2021,Staten\nIsland,Willowbrook,Male,Other/Unknown,0,0,0,NaN,1,153
8975,2021,Staten\nIsland,Willowbrook,Male,White,0,0,0,NaN,3,12.8

Reading the dataset of HIV AIDS Diagnosis by Age, Neighborhood and Race Ethnicity. And creating a dataframe called df_Age

In [9]:

df_Age = pd.read_csv('Dataset/HIV_AIDS_by_Age_Group_by_Neighborhood_and_Race_Ethnicity.csv')
df_Age

,YEAR,NEIGHBORHOOD,RACE/ETHNICITY,AGE,TOTAL NUMBER OF HIV DIAGNOSES,"HIV DIAGNOSES PER 100,000 POPULATION",TOTAL NUMBER OF CONCURRENT HIV/AIDS DIAGNOSES,PROPORTION OF CONCURRENT HIV/AIDS DIAGNOSES AMONG ALL HIV DIAGNOSES,TOTAL NUMBER OF AIDS DIAGNOSES,"AIDS DIAGNOSES PER 100,000 POPULATION",Borough
0,2013,High Bridge - Morrisania,Native American,30 - 39,0,0,0,0,0,0,NaN
1,2010,East Harlem,Unknown,40 - 49,0,NaN,0,NaN,0,NaN,NaN
2,2011,High Bridge - Morrisania,Unknown,40 - 49,0,NaN,0,NaN,0,NaN,NaN
3,2012,Greenwich Village - SoHo,Native American,50 - 59,0,0,0,0,0,0,NaN
4,2011,Long Island City - Astoria,Multiracial,20 - 29,0,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
21031,2021,Willowbrook,Black,60+,0,0,0,NaN,0,0,Staten\nIsland
21032,2021,Willowbrook,Latino/Hispanic,60+,0,0,0,NaN,0,0,Staten\nIsland
21033,2021,Willowbrook,Other/Unknown,60+,0,0,0,NaN,NaN,NaN,Staten\nIsland
21034,2021,Willowbrook,White,60+,0,0,0,NaN,1,5.6,Staten\nIsland
21035,2021,Willowbrook,All,All,4,4.9,0,0,4,4.9,Staten\nIsland